contracts/registry/ClaimVerifier.sol, contracts/registry/IdentityRegistry.sol, contracts/token/TransferManager.sol
I have added the following missing public declarations:
- typesRegistry of IdentityRegistry
- issuersRegistry of ClaimVerifier
- identityRegistry of Token
- compliance of Token
I have added a getIdentities method in IdentityRegistry. It seems I can't return directly the struct array (solidity compiler returns an error:
```
TypeError: This type is only supported in the new experimental ABI encoder. Use "pragma experimental ABIEncoderV2;" to enable the feature.
function getIdentities() public view returns (IdentityContract[]) {
```
So I used a trick to return the list of user addresses and their identities instead.
=> Public declaration and getIdentities

contracts/identity/ERC725.sol
The ERC725 interface is missing the removeKey signature. This PR adds the missing signature so that the KeyHolder contract can fully be exploited using the ERC725 interface.
=> fix(ERC725): Add missing removeKey signature.

contracts/token/IToken.sol, contracts/token/Token.sol
none of the token specifications should be instantiated at interface level, the value should be set at the implementation level. That's why the decimals should just be declared in the `IToken.sol` contract and instantiated in the `Token.sol` contract.
=> Decimals on implementation

contracts/token/IToken.sol
The interface cannot declare constant properties that are not defined.
I have removed the constant declaration from the interface.
=> fix(IToken) Remove constant declaration from interface

contracts/token/IToken.sol, contracts/token/Token.sol, package.json
Decimals were set as constant in the Token Contract.
It is now an updatable information. 
Another possibility would be to add the decimals count in the constructor (because it doesn't make much sense to allow for this info to be updated).
=> 🐛(Token) Add decimals as updatable information

contracts/registry/IdentityRegistry.sol, contracts/token/IToken.sol, contracts/token/Token.sol
I removed the MultiAgent contract and used the RoleAgent contract instead for the IdentityRegistry contract.
I have also fixed an issue with the parameters of the setTokenInformation method (calldata is not allowed for address type).
Order was wrong in the event for version and decimals.
=> Remove duplicate of agent role behavior

contracts/compliance/ICompliance.sol, contracts/compliance/LimitHolder.sol, contracts/registry/ClaimTopicsRegistry.sol, contracts/registry/IClaimTopicsRegistry.sol, contracts/registry/IIdentityRegistry.sol, contracts/registry/ITrustedIssuersRegistry.sol, contracts/registry/IdentityRegistry.sol, contracts/registry/TrustedIssuersRegistry.sol, contracts/token/IToken.sol, package.json, yarn.lock
Interfaces were declare as `contract`, allowing them to declare and holds variables.
I have updated all interfaces declaration from `contract` to proper `interface`, and removed any variable declaration (added public getters methods when they were public) to move them into the implementations.
I have also added solidity-docgen as a dependency to generate a docpage (I'll look for another good documentation or at least a good renderer tool later).
=> ♻️ Declare interface contracts as interfaces

.github/workflows/publish-release.yml, package.json
This workflow build and publish the contract package to NPM and GitHub packages whenever a release tag is created on GitHub.
To publish to NPM, we need to create an account and generate an authorization token that we will add to the secrets of the repository.
=> Add publication github actions

contracts/token/TransferManager.sol, package.json, test/tokenTransfer.test.js
This function will be used to transfer tokens on behalf of an investor without the need of any transaction on the blockchain coming from the sender. This way the sender doesn't need any ETH on his wallet and doesn't need to manage crypto.
=> Create a ForcedTransfer function

contracts/token/TransferManager.sol, package.json, test/tokenTransfer.test.js
forcedTransfer was not possible between partially frozen addresses, which should be the case if we don't want the agent to do 2 transactions (unfreezePartialTokens + forcedTransfer) in the case the amount of free tokens is lower than the amount to transfer, the goal of this PR is to solve this minor issue
=> ♻ forcedTransfer on partial freeze

contracts/compliance/DefaultCompliance.sol, contracts/compliance/ICompliance.sol, contracts/compliance/LimitHolder.sol, contracts/registry/ClaimTopicsRegistry.sol, contracts/registry/IClaimTopicsRegistry.sol, contracts/registry/IIdentityRegistry.sol, contracts/registry/ITrustedIssuersRegistry.sol, contracts/registry/IdentityRegistry.sol, contracts/registry/TrustedIssuersRegistry.sol, contracts/roles/AgentManager.sol, contracts/roles/OwnerManager.sol, contracts/roles/OwnerRoles.sol, contracts/token/IToken.sol, contracts/token/Token.sol, test/ownerManager.test.js, test/registry.test.js, test/tokenTransfer.test.js
this smart contract is intended to be used to increase granularity of the owner role, as the owner role could be too permissive and as the role's permissions are hardcoded in the token smart contracts and not modifiable post-deployment, this external smart contract could be used easily to change the permissions of a role, and a custom version of this smart contract could also be created in case there is a need for even more granularity in the role's permissions. By setting this smart contract as owner on the Token and all the other smart contracts of TREX it allows to get more granularity on the permissions linked to the owner role and it also allows to link this role to the onchainID of the owner which prevent him from losing access to the functions if he loose his private key (as it is …
=> External owner manager

contracts/compliance/DefaultCompliance.sol, contracts/compliance/ICompliance.sol, contracts/compliance/LimitHolder.sol, contracts/registry/ClaimTopicsRegistry.sol, contracts/registry/IClaimTopicsRegistry.sol, contracts/registry/IIdentityRegistry.sol, contracts/registry/ITrustedIssuersRegistry.sol, contracts/registry/IdentityRegistry.sol, contracts/registry/TrustedIssuersRegistry.sol, contracts/roles/AgentManager.sol, contracts/roles/AgentRole.sol, contracts/roles/AgentRoles.sol, contracts/roles/OwnerManager.sol, contracts/roles/OwnerRoles.sol, contracts/token/IToken.sol, contracts/token/Token.sol, package.json, test/agentManager.test.js, test/compliance.test.js, test/identity.test.js, test/ownerManager.test.js, test/registry.test.js, test/tokenTransfer.test.js
those smart contracts are intended to be used to increase granularity of the agent/owner roles, as the roles described at token level could be too permissive and as the role's permissions are hardcoded in the token smart contracts and not modifiable post-deployment, these external smart contracts could be used easily to change the permissions of a role, and a custom version of this smart contract could also be created in case there is a need for even more granularity in the role's permissions. By setting this smart contract as agent/owner on the smart contracts it allows to get more granularity on the permissions linked to the different roles and it also allows to link these roles to the onchainID of the agent/owner which prevent him from losing access to the functions if he loose his …
=> new contracts : AgentManager and OwnerManager

README.md, contracts/compliance/DefaultCompliance.sol, contracts/registry/ClaimTopicsRegistry.sol, contracts/registry/IdentityRegistry.sol, contracts/registry/TrustedIssuersRegistry.sol, contracts/roles/AgentRole.sol, contracts/roles/AgentRoles.sol, contracts/roles/Ownable.sol, contracts/roles/OwnerRoles.sol, contracts/roles/Roles.sol, package.json, yarn.lock
OppenZeppelin overrided their 3.0.0-beta.0 version and removed the Roles.sol and moved the Ownable.sol.
The implementation of Roles is no longer compatible. I imported the old version in our codebase, as well as the old Ownable.
=> ➕() Import ownable and role as they were removed from OZ

contracts/compliance/LimitHolder.sol, contracts/registry/IIdentityRegistry.sol, contracts/registry/IIdentityRegistryStorage.sol, contracts/registry/IdentityRegistry.sol, contracts/registry/IdentityRegistryStorage.sol, contracts/token/Token.sol, package.json, test/agentManager.test.js, test/compliance.test.js, test/ownerManager.test.js, test/registry.test.js, test/tokenTransfer.test.js, yarn.lock
the goal of this PR is to allow several identity registries to share the same list of registered identities while remaining independent in terms of investor eligibility criteria (coming from trusted issuers registry and claim topics registry that are specific to each identity registry).
=> ♻() unbind storage of identities from registry

CHANGELOG.md, contracts/registry/implementation/IdentityRegistry.sol, contracts/registry/implementation/TrustedIssuersRegistry.sol, contracts/registry/interface/ITrustedIssuersRegistry.sol, contracts/registry/storage/TIRStorage.sol, test/registry.test.js
- This prevents from querying claims that would not be allowed because they were emitted from an untrusted issuer.
- This also prevents an Identity Owner to be unable to be verified because they might have too many claims of a given topic.
> **Note**
> Further optimization could be performed if the Trusted Issuer Registry had a method `getTrustedIssuersByClaimTopic(uint256 claimTopic)` (I might implement this on this PR).
Gas cost comparison for a transfer with and without this optimization (minor):
(comparing https://github.com/TokenySolutions/T-REX/actions/runs/3727061919/jobs/6320901174 and https://github.com/TokenySolutions/T-REX/actions/runs/3732257985/jobs/6331470948)
| Operation | With this PR | Without |
| *-------* | ------------ | ------- |
| Transfer  | 155742  | 191913 |
| …
=> ✨(identityRegistry) Compute array of claimIds from trusted issuers

contracts/registry/implementation/IdentityRegistry.sol, test/registry.test.js
Add tests to improve coverage.
We do have an issue with the try/catch that seems to not properly catch the error when the Trusted Issuer in the claim is not a Trusted Issuer contract (the `isVerified` returns a revert).
=> ✅(registries) Add test to cover missing statements

CHANGELOG.md, contracts/compliance/modular/modules/ConditionalTransferModule.sol, contracts/compliance/modular/modules/CountryAllowModule.sol, contracts/compliance/modular/modules/CountryRestrictModule.sol, contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol, contracts/compliance/modular/modules/IModule.sol, contracts/compliance/modular/modules/MaxBalanceModule.sol, contracts/compliance/modular/modules/SupplyLimitModule.sol, contracts/compliance/modular/modules/TimeExchangeLimitsModule.sol, contracts/compliance/modular/modules/TimeTransfersLimitsModule.sol, package-lock.json, test/compliances/module-conditional-transfer.test.ts, test/compliances/module-country-allow.test.ts, test/compliances/module-country-restrict.test.ts, test/compliances/module-exchange-monthly-limits.test.ts, test/compliances/module-supply-limit.test.ts, test/compliances/module-time-exchange-limits.test.ts, test/compliances/module-time-transfer-limits.test.ts
- Add `function name() external pure returns (string memory);` to IModule. Compliance modules now require a `string constant public name = "ConditionalTransferModule";` constant variable to be declared.
=> ✨(modules) Add name to modules

contracts/compliance/modular/modules/TransferFeesModule.sol, index.js, test/compliances/module-transfer-fees.test.ts
Notes:
- The minimum fee rate is 0.01% but must be given in uint format. So, when defining fee rates:
- 1 = 0.01%
- 10 = 0.1%
- 100 = 1%
- 1000 = 10%
- 10000 = 100%
- It can also be 0, which means no fee will be charged
- `canComplianceBind` function is for the plug-and-play support discussed before. It checks whether the module is a token agent (and is required for the module to function). It should be called from the `addComplianceModule`
- This is a draft function, I can update it after we decide how to proceed with the plug-and-play support.
=> (TFM) Add transfer fees module

scripts/flatten.js
Flattening script improvements : 
- showing progress during the flattening process by logging which files are flattened and counting down the remaining files 
- Removes all SPDX identifiers from the flat file (previously 1 per imported contract) and add a unique `SPDX-License-Identifier: GPL-3.0` declaration at the beginning of the flat file. Having multiple SPDX identifiers was blocking the compilation.
- Removes all the pragma solidity declarations in a similar approach. Add a single declaration `pragma solidity 0.8.17` at the beginning of the flat file
- Removes empty lines when more than 2 empty lines in a row for improved structure and clarity on the flat file.
=> Improve flatten script

CHANGELOG.md, contracts/compliance/modular/modules/SupplyLimitModule.sol, package-lock.json, package.json, test/compliances/module-supply-limit.test.ts
- Removed `_compliance` parameter from `setSupplyLimit` function of the `SupplyLimitModule` as it would not be possible to initialize it when deploying trex-suite through the trex factory
=> Remove _compliance parameter from setSupplyLimit function of the SupplyLimitModule

CHANGELOG.md, contracts/proxy/AbstractProxy.sol, contracts/token/TokenStorage.sol, package.json
Proxies were using the storage slot from the ERC-1822 proxy pattern, but instead of using it to store direct implementation we used it to store the address of the Implementation Authority. 
The fact of using this storage slot created issues with the explorers such as polygonscan which believed we used ERC-1822 and displayed the ABI of the Implementation Authority instead of the ABI of the implementation contracts. 
This PR proposes a new storage slot `0x821f3e4d3d679f19eacc940c87acf846ea6eae24a63058ea750304437a62aafc` which is the result of `keccak256("ERC-3643.proxy.beacon")`
=> Modify IA storage slot on proxies

CHANGELOG.md, contracts/DVA/DVATransferManager.sol, contracts/DVA/DVATransferManagerProxy.sol, contracts/DVA/IDVATransferManager.sol, index.d.ts, index.js, package.json, test/dva.test.ts
- DvA Transfer Manager contract proxified
- The DvA manager contract freezes the tokens to be transferred instead of being a vault (so it must be a token agent) 
- Only the token owner (rather than agents) can call setApprovalCriteria, as it is part of the main token settings.
=> Proxify DvA manager and implement token freeze logic

CHANGELOG.md, contracts/compliance/modular/IModularCompliance.sol, contracts/compliance/modular/ModularCompliance.sol, test/compliances/module-country-allow.test.ts
=> TREX-162 : bind and set module

CHANGELOG.md, contracts/compliance/modular/modules/MaxBalanceModule.sol, package.json, test/compliances/module-max-balance.test.ts
- Added **PresetCompleted** event to MaxBalanceModule, which is triggered when the presetCompleted function is called.
=> Add preset completed event to max balance module

CHANGELOG.md, contracts/compliance/modular/modules/ConditionalTransferModule.sol, contracts/compliance/modular/modules/CountryAllowModule.sol, contracts/compliance/modular/modules/CountryRestrictModule.sol, contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol, contracts/compliance/modular/modules/MaxBalanceModule.sol, contracts/compliance/modular/modules/SupplyLimitModule.sol, contracts/compliance/modular/modules/TimeExchangeLimitsModule.sol, contracts/compliance/modular/modules/TimeTransfersLimitsModule.sol, contracts/compliance/modular/modules/TokenListingRestrictionsModule.sol, contracts/compliance/modular/modules/TransferFeesModule.sol, contracts/compliance/modular/modules/TransferRestrictModule.sol, index.d.ts, index.js, package.json, test/compliances/module-time-transfer-limits.test.ts, test/compliances/module-token-listing-restrictions.test.ts, test/compliances/module-transfer-restrict.test.ts
- Added **removeTimeTransferLimit** function to TimeTransferLimitsModule, allows removing time transfer limits for the given limitTime.
- Added **batchSetTimeTransferLimit** and **batchRemoveTimeTransferLimit** functions to TimeTransferLimitsModule, allows setting and removing multiple time transfer limits at once.
- Introduced **Token Listing Restrictions Module**: Investors can determine which tokens they can receive by whitelisting or blacklisting them
Token issuers can choose the listing type they prefer for their tokens:
WHITELISTING: investors must whitelist/allow the token address in order to receive it.
BLACKLISTING: investors can receive the token by default. If they do not want to receive it, they need to blacklist/disallow it.
- Added commercial licensing to all modules of …
=> Compliance modules fixes & improvements

CHANGELOG.md, contracts/compliance/modular/modules/InvestorCountryCapModule.sol, index.d.ts, index.js, test/compliances/module-investor-country-cap.test.ts
https://tokeny.atlassian.net/browse/BT-360
WIP (tests)
=> BT-360 investor country cap module

contracts/compliance/modular/modules/MinTransferByCountryModule.sol, index.d.ts, index.js, test/compliances/module-min-transfer-by-country.ts
https://tokeny.atlassian.net/browse/BT-354
=> BT-354 Minimum transfer by country module
