contracts/registry/IIdentityRegistry.sol
contracts/registry/IdentityRegistry.sol
contracts/token/TransferManager.sol
package.json

Use interfaces for Identities from the latest version on OnchainID (still in beta preview).

➕() Use OnchainID Interfaces

---

.github/workflows/publish-prerelease.yml
.github/workflows/publish-release.yml
.github/workflows/push_checking.yml
package.json

Added:
- Lint and tests on every push
- Publish to npm and github registry with a 'beta' tag on Github prerelease

👷🏻‍♂️ Add tests and publish CI

---

README.md

remove outdated functions and events in readme, we still need to add all the new functions, lot of work here but let's first merge this on master to avoid displaying doc for functions that don't exist anymore

quick update on readme

---

contracts/registry/ITrustedIssuersRegistry.sol
contracts/registry/TrustedIssuersRegistry.sol
contracts/roles/OwnerManager.sol
test/agentManager.test.js
test/compliance.test.js
test/ownerManager.test.js
test/registry.test.js
test/tokenTransfer.test.js

as the implementation of trusted issuers registry was not optimal a lot of changes had to be done, the only problem is that it changes the signature of events emitted by the trusted Issuers Registry.

BREAKING CHANGES : refactoring Issuers registry

---

contracts/registry/IIdentityRegistryStorage.sol
contracts/registry/IdentityRegistryStorage.sol

Changed double mapping into one, identity is now a struct containing the IdentityContract and InvestorCountry

Refactoring identity

---

.github/workflows/publish-prerelease.yml
.github/workflows/publish-release.yml

Fixed publishing scripts for beta tag on pre-releases.

👷🏻‍♂️() Fix publish CI

---

contracts/compliance/DefaultCompliance.sol
contracts/compliance/ICompliance.sol
contracts/compliance/LimitHolder.sol
contracts/token/Token.sol
package.json
test/agentManager.test.js
test/compliance.test.js
test/identity.test.js
test/ownerManager.test.js
test/registry.test.js
test/tokenTransfer.test.js

- add `bindToken` and `unbindToken` functions on Compliance
- add `addTokenAgent` and `removeTokenAgent` functions on Compliance 
- add getters for bound tokens and token agents on Compliance
- test the new standard functions of compliance 
- lint tests

➕(Compliance) add standard functions

---

contracts/registry/IdentityRegistry.sol
test/tokenTransfer.test.js

- Fix identity registry validation (from https://github.com/TokenySolutions/T-REX/pull/83).

🐛() Fix identity registry claim validation

---

README.md

update readme (#108)

---

CHANGELOG.md
contracts/proxy/TokenProxy.sol
contracts/registry/ClaimTopicsRegistry.sol
contracts/token/Storage.sol
package-lock.json
package.json
test/tokenTransfer.test.js

- testing multiple calls to init function
- proxy implements Initializable from OpenZeppelin 
- bug related to Initializable library was allowing multiple calls on init function as the initializer modifier was 
not working properly
- Double spdx identifier on ClaimTopicsRegistry.sol

TREX 3.5.2

---

.solcover.js
.solhintignore
contracts/_testContracts/v_3_5_2/LegacyIA.sol
contracts/_testContracts/v_3_5_2/LegacyProxy.sol
contracts/_testContracts/v_3_5_2/LegacyToken_3_5_2.sol
test/compliance.test.js
test/factory.test.js
test/helpers/artifacts.js
test/proxyManagement.test.js
test/registry.test.js
test/tokenTransfer.test.js

Test coverage hacken

---

contracts/compliance/modular/modules/MaxBalanceModule.sol
index.js
test/compliances/module-max-balance.test.ts

add MaxBalance Module

---

.eslintrc.json
.solhint.json
CHANGELOG.md
contracts/factory/ITREXFactory.sol
contracts/factory/ITREXGateway.sol
contracts/factory/TREXFactory.sol
contracts/factory/TREXGateway.sol
index.d.ts
index.js
package-lock.json
package.json
test/agentRole.test.ts
test/authorities/trex-implementation-authority.test.ts
test/compliances/module-country-restrict.test.ts
test/dvd.test.ts
test/factory.test.ts
test/fixtures/deploy-compliance.fixture.ts
test/fixtures/deploy-full-suite.fixture.ts
test/gateway.test.ts
test/registries/identity-registry.test.ts
test/registries/trusted-issuers-registry.test.ts

TREX gateway

---

.github/workflows/push_checking.yml
CHANGELOG.md
package-lock.json
test/compliances/module-transfer-fees.test.ts
test/compliances/module-transfer-restrict.test.ts
test/dva.test.ts

This PR adds a check on test files linting upon push

Add typescript lint check on push

---

contracts/token/TokenStorage.sol
package.json

PR to be merged right before merging #165 to update version on token and package

Update package version

---

CHANGELOG.md
contracts/compliance/modular/modules/SupplyLimitModule.sol
package-lock.json
package.json
test/compliances/module-supply-limit.test.ts

- **Compliance Modules**:
- Removed `_compliance` parameter from `setSupplyLimit` function of the `SupplyLimitModule`

🔖(version) Update version to 4.1.2

---

CHANGELOG.md
contracts/token/IToken.sol
contracts/token/Token.sol
test/token/token-recovery.test.ts

TREX-121 : recovery function update

---

CHANGELOG.md
contracts/registry/implementation/IdentityRegistry.sol
contracts/registry/interface/IIdentityRegistry.sol
contracts/registry/storage/IRStorage.sol
test/registries/identity-registry.test.ts

TREX-84 optional eligibility checks

---

CHANGELOG.md
contracts/_testContracts/MockContract.sol
contracts/utilities/IUtilityChecker.sol
contracts/utilities/UtilityChecker.sol
contracts/utilities/UtilityCheckerProxy.sol
hardhat.config.ts
package-lock.json
package.json
test/utilities/compliance-check.test.ts
test/utilities/eligibility-check.test.ts
test/utilities/freeze-check.test.ts
test/utilities/transfer-check.test.ts
test/utilities/upgrade.test.ts

https://tokeny.atlassian.net/browse/BT-47
https://tokeny.atlassian.net/browse/BT-48

BT-47: Eligibility and compliance checker

---

contracts/compliance/modular/modules/InitialLockupPeriodModule.sol
test/compliance.test.ts
test/compliances/module-initial-lockup-period.test.ts
test/compliances/module-max-balance.test.ts
test/fixtures/deploy-full-suite.fixture.ts

https://tokeny.atlassian.net/browse/BT-385

BT-385 Add InitialLockupPeriod module

---

contracts/utils/OwnableOnceNext2StepUpgradeable.sol
test/compliance.test.ts
test/compliances/module-conditional-transfer.test.ts
test/compliances/module-country-allow.test.ts
test/compliances/module-country-restrict.test.ts
test/compliances/module-exchange-monthly-limits.test.ts
test/compliances/module-max-balance.test.ts
test/compliances/module-supply-limit.test.ts
test/compliances/module-time-exchange-limits.test.ts
test/compliances/module-time-transfer-limits.test.ts
test/compliances/module-token-listing-restrictions.test.ts
test/compliances/module-transfer-fees.test.ts
test/compliances/module-transfer-restrict.test.ts
test/dva.test.ts
test/registries/claim-topics-registry.test.ts
test/registries/identity-registry-storage.test.ts
test/registries/identity-registry.test.ts
test/registries/trusted-issuers-registry.test.ts
test/token/token-agent-restrictions.test.ts
test/token/token-information.test.ts
test/token/token-transfer.test.ts

https://tokeny.atlassian.net/browse/BT-624
`forge inspect --hardhat contracts/DVA/DVATransferManager.sol:DVATransferManager storageLayout `
> ╭-------------------+-----------------------------------------------------------------+------+--------+-------+---------------------------------------------------------╮
> | Name              | Type                                                            | Slot | Offset | Bytes | Contract                                                |
> +=======================================================================================================================================================================+
> | _initialized      | uint8                                                           | 0    | 0      | 1     | …

Correct storage overlap for OwnableOnceThen2StepUpgradeable

---

contracts/compliance/modular/modules/AbstractModuleUpgradeable.sol
contracts/compliance/modular/modules/ConditionalTransferModule.sol
contracts/compliance/modular/modules/CountryAllowModule.sol
contracts/compliance/modular/modules/CountryRestrictModule.sol
contracts/compliance/modular/modules/ExchangeMonthlyLimitsModule.sol
contracts/compliance/modular/modules/InvestorCountryCapModule.sol
contracts/compliance/modular/modules/MaxBalanceModule.sol
contracts/compliance/modular/modules/MinTransferByCountryModule.sol
contracts/compliance/modular/modules/SupplyLimitModule.sol
contracts/compliance/modular/modules/TimeExchangeLimitsModule.sol
contracts/compliance/modular/modules/TimeTransfersLimitsModule.sol
contracts/compliance/modular/modules/TransferFeesModule.sol
contracts/compliance/modular/modules/TransferRestrictModule.sol
test/compliances/module-conditional-transfer.test.ts
test/compliances/module-country-allow.test.ts
test/compliances/module-country-restrict.test.ts
test/compliances/module-exchange-monthly-limits.test.ts
test/compliances/module-investor-country-cap.test.ts
test/compliances/module-max-balance.test.ts
test/compliances/module-min-transfer-by-country.ts
test/compliances/module-supply-limit.test.ts
test/compliances/module-time-exchange-limits.test.ts
test/compliances/module-time-transfer-limits.test.ts
test/compliances/module-token-listing-restrictions.test.ts
test/compliances/module-transfer-fees.test.ts
test/compliances/module-transfer-restrict.test.ts

https://tokeny.atlassian.net/browse/BT-72
https://tokeny.atlassian.net/browse/BT-74
https://tokeny.atlassian.net/browse/BT-75

BT-72 Reset state of modules on unbind

---

contracts/compliance/modular/modules/TransferFeesModule.sol
test/compliances/module-transfer-fees.test.ts

https://tokeny.atlassian.net/browse/BT-580

BB-580 fee whitelist
